name: Deploy with Docker to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Rename jar to app.jar
        run: cp build/libs/*SNAPSHOT.jar build/libs/app.jar
        
      ######################################
      ##  Docker Hub에 Push 
      ######################################
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t spring-app .

      - name: Tag image for Docker Hub
        run: docker tag spring-app ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-app:latest
        
      ######################################
      ##  EC2로 배포
      ######################################
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add known hosts
        run: ssh-keyscan -t ed25519 43.203.225.194 >> ~/.ssh/known_hosts

      - name: Upload JAR and Dockerfile to server
        run: |
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no build/libs/app.jar ubuntu@43.203.225.194:~/app/app.jar
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no Dockerfile ubuntu@43.203.225.194:~/app/Dockerfile

      - name: Build and Run Docker image on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@43.203.225.194 << 'EOF'
            cd ~/app
            sudo docker stop spring-app || true
            sudo docker rm spring-app || true
            sudo docker rmi spring-app:latest || true
            sudo docker build -t spring-app:latest .
            sudo docker run -d --name spring-app -p 8080:8080 --restart unless-stopped spring-app:latest
          EOF
